<div class="row">
    <div class="col-md-12 text-center">
        <h1>Classements</h1>
        <hr/>
        <h2>Choix du classement</h2>
        <select id="choix_classement">
            <option value="general">Général</option>
            <option value="hommes">Hommes</option>
            <option value="femmes">Femmes</option>
        </select>


        <?php foreach ($classements as $key => $classement) {?>
            <div id="classement_<?= $key?>">

                <?php if ($key == 'general') {?>
                    <h2>Classement Général</h2>
                <?php } else if ($key == 'hommes') {?>
                    <h2>Classement Hommes</h2>
                <?php } else if ($key == 'femmes') {?>
                    <h2>Classement Femmes</h2>
                <?php } ?>
                <div class="table-responsive mt-20">
                    <table class="table">
                        <thead>
                        <tr>
                            <td>Dossard n°</td>
                            <td>Nom</td>
                            <td>Prénom</td>
                            <?php if ($key == 'general') {?>
                                <td>Sexe</td>
                            <?php } ?>
                            <td>Evènement</td>
                            <td>Temps</td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>
                            <?php
                            /** @var \Application\Entity\User $participant */
                            foreach ($classement as $participant) { ?>
                                <?php if ($key == 'hommes' && $participant->getSex() == 'female') {?>
                                    <?php continue; ?>
                                <?php } ?>

                                <?php if ($key == 'femmes' && $participant->getSex() == 'male') {?>
                                    <?php continue; ?>
                                <?php } ?>
                                    <tr>
                                        <td><?=$participant->getNumDossard()?></td>
                                        <td><?=$participant->getFirstname()?></td>
                                        <td><?=$participant->getLastname()?></td>
                                        <?php if ($key == 'general') {?>
                                            <td><?=$participant->getSex()?></td>
                                        <?php } ?>
                                        <td><?=$participant->getEvent()->getName()?></td>
                                        <td><?=$participant->getDuration()?></td>
                                    </tr>

                            <?php } ?>

                        </tbody>
                    </table>
                </div>
            </div>
        <?php }?>

    </div>
</div>

<script type="text/javascript" src="/js/jquery-3.1.0.js"></script>
<script type="text/javascript" src="/js/jquery.mask.js"></script>
<script type="text/javascript" src="/js/script.js"></script>
